variables:
  reg_password: $reg_password
  reg_username: $reg_username

stages:
  - debug


build:
  stage: debug
  script:
  - env
  - echo ${CI_REGISTRY_IMAGE}
  - docker login git.gueznet.local -u $reg_username -p $reg_password
  - docker pull git.gueznet.local/repos/secmon:latest || true
  - docker build . -t git.gueznet.local/repos/secmon:latest
  - docker push git.gueznet.local/repos/secmon:latest
