variables:
  reg_password: $reg_password
  reg_username: $reg_username

stages:
  - build
  - vuln_scan
  - malware_scan
  - test
  - release_image
  - release_github

Build-Image:
  stage: build
  script:
  - docker login registry.gueznet.local:443 -u $reg_username -p $reg_password
  - docker pull registry.gueznet.local:443/repos/secmon:latest || true
  - docker build . -t registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - docker push registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG

Vuln-Scan:
  stage: vuln_scan
  variables:
    ANCHORE_CLI_URL: "http://anchore-engine:8228/v1"
    GIT_STRATEGY: none
  image: docker.io/anchore/inline-scan:latest
  services:
  - name: docker.io/anchore/inline-scan:latest
    alias: anchore-engine
    command: ["start"]
  
  script:
  - anchore-cli system wait
  - anchore-cli registry add registry.gueznet.local:443 gitlab-ci-token "$CI_JOB_TOKEN" --skip-validate --insecure
  - anchore-cli image add registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - anchore-cli image wait registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - anchore-cli evaluate check --detail registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
#  - anchore_ci_tools.py -a -r --timeout 500 --image registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG


Malware-Scan:
  stage: malware_scan
  script:
  - echo ''

Test:
  stage: test
  script:
  - echo ''

Release-Image:
  stage: release_image
  script:
  - docker login registry.gueznet.local:443 -u $reg_username -p $reg_password
  - docker tag registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG registry.gueznet.local:443/repos/secmon:latest
  - docker push registry.gueznet.local:443/repos/secmon:latest


Github-Push:
  stage: release_github
  script:
  - echo ''

