# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
variables:
  reg_password: $reg_password
  reg_username: $reg_username
  CI_REGISTRY_IMAGE: 'secmon'


build:
  script:
  - docker login git.gueznet.local -u $reg_username -p $reg_password
  - docker pull $CI_REGISTRY_IMAGE:latest || true
  - docker build --cache-from -t $CI_REGISTRY_IMAGE .
  - docker push $CI_REGISTRY_IMAGE:latest
