variables:
  reg_password: $reg_password
  reg_username: $reg_username
  docker_hub_password: $docker_hub_password
  docker_hub_login: $docker_hub_login

stages:
  - build
  - vuln_scan
  - malware_scan
  - test
  - release_image
  - release_github

Build-Image:
  stage: build
  script:
  - docker login registry.gueznet.local:443 -u $reg_username -p $reg_password
  - docker pull registry.gueznet.local:443/repos/secmon:latest || true
  - docker build . -t registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - docker push registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  allow_failure: false

Vuln-Scan:
  stage: vuln_scan
  variables:
    ANCHORE_CLI_URL: "http://anchore-engine:8228/v1"
    GIT_STRATEGY: none
  image: docker.io/anchore/inline-scan:latest
  services:
  - name: docker.io/anchore/inline-scan:latest
    alias: anchore-engine
    command: ["start"]
  allow_failure: false
  
  script:
  - anchore-cli system wait
  - anchore-cli registry add registry.gueznet.local:443 gitlab-ci-token "$CI_JOB_TOKEN" --skip-validate --insecure
  - anchore-cli image add registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - anchore-cli image wait registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - anchore-cli image vuln registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG all
#  - anchore-cli evaluate check --detail registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
#  - anchore_ci_tools.py -a -r --timeout 500 --image registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG

Malware-Scan:
  stage: malware_scan
  script:
  - docker stop secmon-test && docker rm secmon-test || true
  - docker login registry.gueznet.local:443 -u $reg_username -p $reg_password
  - docker run -i -t --name secmon-test --expose 80 --expose 443 -d registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - docker cp . secmon-test:/var/www/secmon
  - docker exec secmon-test bash -c 'apt update && apt install -y clamav && freshclam'
  - docker exec secmon-test bash -c 'cd /var/www/secmon && python3 -c "import secmon_lib" && python3 -c "from secmon_web import *" 2>/dev/null' || true
  - docker exec secmon-test clamscan --remove  --infected -r /var/www/secmon | tee scan-results.txt
  - docker exec secmon-test clamscan --remove --infected -r /usr/local/lib/ | tee -a scan-results.txt 
  - docker stop secmon-test && docker rm secmon-test 
  allow_failure: true

Test:
  stage: test
  script:
  - docker stop secmon-test && docker rm secmon-test || true
  - docker login registry.gueznet.local:443 -u $reg_username -p $reg_password
  - docker run -i -t --name secmon-test --expose 80 --expose 443 -d registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - docker cp . secmon-test:/var/www/secmon
  - docker exec secmon-test bash -c 'cd /var/www/secmon && python3 -c "import secmon_lib" && python3 -c "from secmon_web import *"'
  - docker stop secmon-test && docker rm secmon-test 
  allow_failure: true

Release-Image:
  stage: release_image
  script:
  - docker login registry.gueznet.local:443 -u $reg_username -p $reg_password
  - docker tag registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG registry.gueznet.local:443/repos/secmon:latest
  - docker push registry.gueznet.local:443/repos/secmon:latest
  - docker login registry-1.docker.io -u $docker_hub_password -p $docker_hub_login
  - docker tag registry.gueznet.local:443/repos/secmon:latest guezone/secmon:latest
  - docker push guezone/secmon:latest
  allow_failure: false

Github-Push:
  stage: release_github
  script:
  - echo ''

