variables:
  reg_password: $reg_password
  reg_username: $reg_username

stages:
  - build
  - scan


Build Image:
  stage: build
  script:
  - env
  - echo ${CI_REGISTRY_IMAGE}
  - docker login registry.gueznet.local:443 -u $reg_username -p $reg_password
  - docker pull registry.gueznet.local:443/repos/secmon:latest || true
  - docker build . -t registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG
  - docker push registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG

container_scan_service:
  stage: scan
  variables:
    ANCHORE_CLI_URL: "http://anchore-engine:8228/v1"
    GIT_STRATEGY: none
  image: docker.io/anchore/inline-scan:latest
  services:
  - name: docker.io/anchore/inline-scan:latest
    alias: anchore-engine
    command: ["start"]
  
  script:
  - anchore-cli system wait
  - anchore-cli registry add registry.gueznet.local:443 gitlab-ci-token "$CI_JOB_TOKEN" --skip-validate --insecure
  - anchore_ci_tools.py -a -r --timeout 500 --image registry.gueznet.local:443/repos/secmon:$CI_COMMIT_REF_SLUG

  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}
    paths:
    - anchore-reports/*
