variables:
  reg_password: $reg_password
  reg_username: $reg_username

stages:
  - debug


build:
  stage: debug
  script:
  - env
  - echo ${CI_REGISTRY_IMAGE}
  - docker login registry.gueznet.local:443 -u $reg_username -p $reg_password
  - docker pull registry.gueznet.local:443/repos/secmon:latest || true
  - docker build . -t registry.gueznet.local:443/repos/secmon:latest
  - docker push registry.gueznet.local:443/repos/secmon:latest
