# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
- build
- sast
build:
  stage: build
  script:
  - docker build -t guezone/secmon:latest .
sast:
  stage: sast
include:
- template: Auto-DevOps.gitlab-ci.yml
