variables:
  PRIVATE_REGISTRY_PASSWD: $PRIVATE_REGISTRY_PASSWD
  PRIVATE_REGISTRY_USERNAME: $PRIVATE_REGISTRY_USERNAME
  DOCKER_HUB_PASSWD: $DOCKER_HUB_PASSWD
  DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME

stages:
  - build
  - vuln_scan
  - malware_scan
  - test
  - release_image
  - release_github

Build-Image:
  stage: build
  script:
  - docker login registry.gueznet.local:443 -u $PRIVATE_REGISTRY_USERNAME -p $PRIVATE_REGISTRY_PASSWD
  - docker pull $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:latest || true
  - docker build . -t $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:$CI_COMMIT_REF_SLUG
  - docker push $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:$CI_COMMIT_REF_SLUG
  allow_failure: false

Vuln-Scan:
  stage: vuln_scan
  variables:
    ANCHORE_CLI_URL: "http://anchore-engine:8228/v1"
    GIT_STRATEGY: none
  image: docker.io/anchore/inline-scan:latest
  services:
  - name: docker.io/anchore/inline-scan:latest
    alias: anchore-engine
    command: ["start"]
  script:
  - anchore-cli system wait
  - anchore-cli registry add registry.gueznet.local:443 gitlab-ci-token "$CI_JOB_TOKEN" --skip-validate --insecure
  - anchore-cli image add $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:$CI_COMMIT_REF_SLUG
  - anchore-cli image wait $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:$CI_COMMIT_REF_SLUG
  - anchore-cli image vuln $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:$CI_COMMIT_REF_SLUG all
  allow_failure: true

Malware-Scan:
  stage: malware_scan
  script:
  - docker stop secmon-test && docker rm secmon-test || true
  - docker login registry.gueznet.local:443 -u $PRIVATE_REGISTRY_USERNAME -p $PRIVATE_REGISTRY_PASSWD
  - docker run -i -t --name secmon-test --expose 80 --expose 443 -d $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:$CI_COMMIT_REF_SLUG
  - docker cp . secmon-test:/var/www/secmon
  - docker exec secmon-test bash -c 'apt update && apt install -y clamav && freshclam'
  - docker exec secmon-test bash -c 'cd /var/www/secmon && python3 -c "import secmon_lib" && python3 -c "from secmon_web import *" 2>/dev/null' || true
  - docker exec secmon-test clamscan --remove  --infected -r /var/www/secmon | tee scan-results.txt
  - docker exec secmon-test clamscan --remove --infected -r /usr/local/lib/ | tee -a scan-results.txt 
  - docker stop secmon-test && docker rm secmon-test 
  allow_failure: true

Test:
  stage: test
  script:
  - docker stop secmon-test && docker rm secmon-test || true
  - docker login registry.gueznet.local:443 -u $PRIVATE_REGISTRY_USERNAME -p $PRIVATE_REGISTRY_PASSWD
  - docker run -i -t --name secmon-test --expose 80 --expose 443 -d $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:$CI_COMMIT_REF_SLUG
  - docker cp . secmon-test:/var/www/secmon
  - docker exec secmon-test bash -c 'cd /var/www/secmon && python3 -c "import secmon_lib" && python3 -c "from secmon_web import *"'
  - docker stop secmon-test && docker rm secmon-test 
  allow_failure: true

Release-Image:
  stage: release_image
  script:
  - docker login registry.gueznet.local:443 -u $PRIVATE_REGISTRY_USERNAME -p $PRIVATE_REGISTRY_PASSWD
  - docker tag $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:$CI_COMMIT_REF_SLUG $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:latest
  - docker push $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:latest
  - docker login -u $DOCKER_HUB_PASSWD -p $DOCKER_HUB_USERNAME
  - docker tag $SECMON_REGISTRY_IMAGE_WITHOUT_TAG:latest guezone/secmon:latest
  - docker push guezone/secmon:latest
  allow_failure: false

Github-Push:
  stage: release_github
  script:
  - echo 'to do'

