variables:
  reg_password: $reg_password
  reg_username: $reg_username

stages:
  - debug


build:
  stage: debug
  script:
  - env
  - echo ${CI_REGISTRY_IMAGE}
  - docker login git.gueznet.local -u $reg_username -p $reg_password
  - docker pull ${CI_REGISTRY_IMAGE}:latest || true
  - docker build -t ${CI_REGISTRY_IMAGE} .
  - docker push ${CI_REGISTRY_IMAGE}:latest
